# Default values for analyze.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: supergiant/analyze
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  externalPort: 4443
  internalPort: 9091

ingress:
  enabled: false

resources:
  requests:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Set default image settings and persistence settings of etcd
etcd:
  ## For available images please check: https://hub.docker.com/r/pachyderm/etcd/tags or: https://quay.io/repository/coreos/etcd?tag=latest&tab=tags
  image:
    repository: quay.io/coreos/etcd
    tag: v3.3.5
    pullPolicy: IfNotPresent
    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    enabled: false
    ## etcd data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner. (gp2 on AWS, standard on
    ## GKE, AWS & OpenStack)
    # storageClass: "-"
    ## Set default PVC size
    size: 20G
    ## Set default PVC access mode: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    accessMode: ReadWriteOnce
  resources:
    ## For non-local deployments, 1 cpu and 2G of memory requests are recommended
    requests:
      cpu: 250m
      memory: 256M

cloudProviderType: "aws" ## need to be enum "aws", "do".

## TODO: it is nice to make these properties discoverable
aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: ""
