apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analyze.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "analyze.name" . }}
    helm.sh/chart: {{ include "analyze.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "analyze.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "analyze.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.etcd.enable }}
            - name: ETCD_DISCOVERY_DOMAIN
              value: {{default (printf "%s-etcd" .Release.Name | trunc 63) .Values.etcd.discovery }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
              - name: config-volume
                mountPath: "/etc/analyzed"
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: config-volume
        configMap:
          name: default-config
